version: '3.7'

services:
  db:
    image: postgres:9.6.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: "redis:alpine"
  api:
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./magic/.env
    depends_on:
      - db
  celery:
    build: .
    command: celery -A magic worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery-beat:
    build: .
    command: celery -A magic beat -l info
    volumes: 
      - .:/code
    depends_on: 
      - db
      - redis
volumes:
  postgres_data:
